Make golangci-lint happy with error checking
Issues seen:
```
$ golangci-lint run
main_test.go:38:16: Error return value of `w.Close` is not checked (errcheck)
		defer w.Close()
		             ^
main_test.go:523:20: Error return value of `udpListener.Close` is not checked (errcheck)
		udpListener.Close()
		                 ^
main_test.go:530:20: Error return value of `tcpListener.Close` is not checked (errcheck)
		tcpListener.Close()
		                 ^
3 issues:
* errcheck: 3
```

Actually calling Close() on udpListener and tcpListener resulted in an
error because the deferred shutdown calls already handle that so just
remove them:
```
main_test.go:539: [...]: close tcp 127.0.0.1:62627: use of closed network connection
main_test.go:529: [...]: close udp 127.0.0.1:53310: use of closed network connection
```